### PR TITLE
Only update new files

### PR DESCRIPTION
**Pull request by HannesOberreiter**
Added option to only update new/changed files. This does not work on every server you may add `--ignore-time`, then it will only look if the file size is different. This could make troubles but should be fine most of the time.

### CODE REVIEW

**Comment by kevinpainchaud** [comment]
Hello,
Thank you for your participation and sorry for the response time. I have just returned from my summer vacation.
I really like the idea to not sending the unmodified files.
I will test this new option soon and merge it if it's successful.

**Comment by kevinpainchaud** [comment]
Hello,
I added this 2 news options : `only_newer`, `ignore_time`.
Can you test on this feature branch ? https://github.com/kevinpainchaud/simple-ftp-deploy-action/tree/feature-only-newer
(In your `main.yml`, you can refer to it like this : `uses: kevinpainchaud/simple-ftp-deploy-action@feature-only-newer`)
If it's works for you, i'm gonna release this into a new version. 😊
Thx.

**Comment by HannesOberreiter** [comment]
Hi,

seems to be working. First image is with standard and false settings (you can see its overwriting eg. the empty .nojekyll file), second one is with both params as "true" (no more .nojekyll, only the .gz sitemap - prob. due to zipping - and then the new generated folders from nuxt generate).

I think thats the best solution to let both params be picked by the user. But as I mentioned at the beginning we may need to add a warning in the readme, when people are using the ignore time. Because if you only make a minor change to a file, lets say exchange the position of two numbers, the file size wont change - but that will probably happen really seldom.

> Ignore size when deciding whether to download. Default "false".

Also the text should be changed to timestamp.

False Flags

True Flags

**Comment by kevinpainchaud** [comment]
Great, thanks for testing this out!
Yes, I also think it's a good idea to leave both options.
And thank you very much for your PR #5 🙏, I just merged it.

**Comment by DanielRuf** [comment]
Short question, does this work with `delete` too? I do not yet know so much about lftp internals.

**Comment by kevinpainchaud** [comment]
Yes, you just have to add this input : [`delete: "true"`](https://github.com/kevinpainchaud/simple-ftp-deploy-action#delete)

**Pull request merged**
